### PR TITLE
rspec and db migration changes

### PR DESCRIPTION
**Pull request by tigersabre**
Add [#1](https://github.com/sagranja/chx/issues/2)

### CODE REVIEW

**Review by AnnessaBW — APPROVED** [review]
This looks awesome, Sarosh! Very thorough. I see you have adopted the wireframes additions for comments and avatar. Thats great! I think we are good to merge - Lets get one more okay - I will post a note in slack for the team to take a look. From there I can move into our STI model updates. Thank you!

**Review by jake-rickard — APPROVED** [review]
Looks good to me!

**Comment by grel4d** [comment]
Great work, Sarosh!

**Comment by AnnessaBW** [comment]
@tigersabre before we merge this I have a couple QQs: 

1) Can we please move the editor configuration files `idea.xml` to .gitignore? That way we aren't all downloading it unnecessarily.

2) Can you please elaborate on `u_id`? I see it is used in a few places and I am not familiar with the phrase or what u would stand for - I see user id is used as well. 

Thank you! 

nes

**Comment by tigersabre** [comment]
1. Sure, we can add that to .gitignore
2. So strangely, id wasn't being accepted as a variable name in the migration files - I think it's already implicitly defined elsewhere and a type of reserved keyword.  I changed it to u_id, which was accepted.  Admittedly, this can be confused with user_id.  We can make it something else

**Comment by tigersabre** [comment]
Also, I didn't see the wireframes, everything I added was already in the schema design you proposed :)

**Comment by AnnessaBW** [comment]
Gotcha, I should have added notes about the yellow highlighted items on the schema too! They are optional - no worries to me if we lose or keep them. Our wireframes link is here on our wiki. 

1) Sounds awesome, thank you!
2) That's interesting! You know, you raise a really good point there. Do we need top specify we need IDs for those classes or are they automatically generated? I was reviewing grammable and I don't see ID listed as a field so I've changed the first line to replace or remove `id` Also - I think it would be wise to add the indexes now too - thoughts? Here are the updates/corrections: 

https://docs.google.com/spreadsheets/d/1pRn0xmhla3mzGt74ICSlIgc8iwWDuqq5d_Jyk1axAOY/edit?usp=sharing.

**Comment by AnnessaBW** [comment]
I asked Joe to review the updated on the db structure too 👍

**Review by josephferrairo — CHANGES_REQUESTED** [review]
A few notes
1. What is `u_id`. It was not in the Google sheet. We should be copying the google sheet for this particular task in order to simulate what it is like working with a team. If there are any changes they should have gone through the same process.
2. Please remove any `.idea` files or add them to `.gitignore`
3. Avatar and Comments shouldn't be added at this time. 
4. These tasks should not be merged together in one PR. It is fine for this one but in the future, for example, this task should have been 2 PRs, one for Rspec and one for migrations.

**Comment by AnnessaBW** [comment]
@tigersabre @josephferrairo - thank you for the notes! I updated the sheet to remove or replace `id` since Sarosh mentioned it was not accepting it (above), so he used `u_id` instead - although it was on our original, approved sheet. Sorry about the confusion there. I have removed avitar and comments from the DB structure.

**Review by grel4d — APPROVED** [review]

**Comment by josephferrairo** [comment]
@AnnessaBW What is `u_id`? If I recall it was not on the original sheet that I approved and neither was avatar or comments. If you are using `black_player_id` and `white_player_id` there is no need for a 3rd `user_id` column.

**Comment by AnnessaBW** [comment]
@josephferrairo - id on the approved form... Sarosh could not add id, it gave him an error. He added u_id instead. I'll posted a screenshot of the original version in slack. The changes were made to change to black_player, white_player from player a and b. Also you asked me to change the positions to x and y - however the user column remained along with the id line.

**Comment by tigersabre** [comment]
Hi all,

id field wasn't being accepted in migration so u changed it to u_id.
However, since we're changing all this, will perform a new migration and
correct it.

Sarosh

**Comment by josephferrairo** [comment]
@tigersabre you don't need to add `id` to your migration. It is automatically added to any table in rails.

**Comment by tigersabre** [comment]
I'm closing this pull request, instead of merging this, I've redone the models in one pull request and the travis, rspec, and gitignore items in the second request.

**Pull request closed without merging**
