### PR TITLE
King, knight, rook, and pawn

### PR DESCRIPTION
**Pull request by grel4d**

### CODE REVIEW

**Review by AnnessaBW — COMMENTED** [review]
Hi @grel4d QQ: What are these symbols following some of the arguments? For example - line 4 of the pawn model - What do they do? Thanks!

**Comment by grel4d** [comment]
These are the positions that the pieces are moving to on the x and y axis @AnnessaBW

**Comment by AnnessaBW** [comment]
image

@grel4d Im referring to these little boxes at the ends of line 4 and 5

**Comment by grel4d** [comment]
Weird - I don’t see those on my end. I’m unsure?? (Currently on my phone so it’s not allowing me to attach a photo)

**Review by AnnessaBW — APPROVED** [review]
Super weird! Could be a browser thing on my end - approving so you can merge :)

**Review by jake-rickard — APPROVED** [review]

**Pull request merged**
